name: ERC 20 Workload
description: |
  ERC-20 Token Transfer Workload - Tests ERC-20 token transfer performance to simulate DeFi workloads and measure contract interaction overhead.

  This benchmark calls the `moveErc20(uint256,bytes)` function to simulate token transfers, providing insights into contract execution performance and gas consumption patterns typical of DeFi applications.

  Use Case: Simulate DeFi workloads, measure contract interaction overhead, validate ERC-20 token performance, and benchmark smart contract execution under realistic transaction patterns.

  Reference: https://github.com/base/fp-test-cases/blob/main/src/ERC20Transfer.sol

payloads:
  - name: ERC 20 Workload
    id: erc20
    type: contract
    calls_per_block: 1
    function_signature: moveErc20(uint256,bytes)
    contract_bytecode: ERC20Transfer
    gas_per_tx: 10000000

benchmarks:
  - variables:
      - type: payload
        value: erc20
      - type: node_type
        values:
          - geth
          - reth
      - type: num_blocks
        value: 10
      - type: gas_limit
        value: 1000000000
