name: SLoad Performance
description: |
  Storage Read Performance Test - Tests storage read (SLOAD) operation performance to optimize storage read operations and compare client storage implementation efficiency.

  This benchmark calls the `reader(uint256,bytes)` function to measure storage access speed, helping identify bottlenecks in storage read operations across different execution clients.

  Use Case: Optimize storage read operations, compare client storage implementation efficiency, and validate storage layer performance under various conditions.

  Reference: https://github.com/base/fp-test-cases/blob/main/src/Reader.sol

payloads:
  - name: SLoad Performance
    id: sload
    type: contract
    calls_per_block: 1
    function_signature: reader(uint256,bytes)
    gas_per_tx: 10000000
    contract_bytecode: Precompile

benchmarks:
  - variables:
      - type: payload
        value: sload
      - type: node_type
        values:
          - geth
          - reth
      - type: num_blocks
        value: 5
      - type: gas_limit
        value: 1000000000
