name: Two-Tier Snapshot Functionality Test
description: |
  Two-Tier Snapshot Functionality Test - Demonstrates the new optimized snapshot system with initial snapshots and per-test copying.

  This benchmark suite uses a two-tier snapshot approach:
  1. Initial snapshots are downloaded once at benchmark startup and stored persistently
  2. Per-test snapshots are copied from initial snapshots for each test run using rsync
  3. Test-specific copies are cleaned up after each test while preserving initial snapshots

  Use Case: Optimized snapshot performance for fast test execution, reduced network overhead, and efficient storage management across multiple node types.

payloads:
  - name: Transfer-only
    id: transfer-only
    type: transfer-only

benchmarks:
  - initial_snapshots:
      - node_type: reth
        # Download an initial reth snapshot that can be copied for each test
        command: ./scripts/setup-initial-snapshot.sh --network=sepolia --node-type=reth --destination=/data/snapshots/reth/initial
        destination: /data/snapshots/reth/initial
        superchain_chain_id: 84532
      - node_type: geth  
        # Download an initial geth snapshot that can be copied for each test
        command: ./scripts/setup-initial-snapshot.sh --network=sepolia --node-type=geth --destination=/data/snapshots/geth/initial
        destination: /data/snapshots/geth/initial
        superchain_chain_id: 84532
    variables:
      - type: payload
        value: transfer-only
      - type: node_type
        values:
          - reth
          - geth
      - type: num_blocks
        value: 10
      - type: gas_limit
        values:
          - 15000000
          - 30000000
          - 60000000
          - 90000000
