name: Snapshot Functionality Test
description: |
  Snapshot Functionality Test - Tests client snapshot creation and loading capabilities to validate state snapshot performance for fast sync operations.

  This benchmark suite tests snapshot functionality with both Sepolia Alpha and development network data, including snapshot creation, loading, and validation processes. Features skip-if-nonempty optimization for development efficiency and tests multiple gas limit configurations.

  Use Case: Validate state snapshot performance for fast sync operations, test snapshot creation and loading capabilities across different environments, and ensure snapshot performance remains consistent in development workflows.

payloads:
  - name: Transfer-only
    id: transfer-only
    type: transfer-only

benchmarks:
  - snapshot:
      # skip non-empty for testing so we don't copy every time we run this
      # just delete the snapshot directory to force a full copy
      command: ./scripts/setup-snapshot.sh --skip-if-nonempty
      genesis_file: ../../sepolia-alpha/sepolia-alpha-genesis.json
    # force_clean is true by default to ensure consistency, but we can skip it for testing
    force_clean: false
    variables:
      - type: payload
        value: transfer-only
      - type: node_type
        values:
          - reth
      - type: num_blocks
        value: 10
      - type: gas_limit
        values:
          - 15000000
          - 30000000
          - 60000000
          - 90000000
  - variables:
      - type: payload
        value: transfer-only
      - type: node_type
        values:
          - reth
      - type: num_blocks
        value: 10
      - type: gas_limit
        values:
          - 15000000
          - 30000000
          - 60000000
          - 90000000
