- name: Test op-reth Performance
  description: Reth Execution Speed
  benchmark:
    - sequencer
  variables:
    - type: transaction_workload
      values:
        - transfer-only
    - type: node_type
      values:
        - reth
        - geth
    - type: num_blocks
      value: 20