- name: Test geth Performance
  description: Geth Execution Speed
  benchmark:
    - sequencer
  variables:
    - type: transaction_workload
      values:
        - tool:tx-fuzz
    - type: node_type
      values:
        - geth