- name: Test Performance
  description: Execution Speed
  variables:
    - type: transaction_workload
      values:
        - transfer-only
    - type: node_type
      values:
        - reth
        - geth
    - type: num_blocks
      value: 20
    - type: gas_limit
      value: 10000000000