- name: Basic EC Pairing Precompile
  description: https://github.com/base/fp-test-cases/blob/main/src/Precompiler.sol
  benchmark:
    - sequencer
  variables:
    - type: transaction_workload
      values:
        - contract:1:ecpairing(uint256,bytes):10000000:0x:./contracts/ecpairing.hex
    - type: node_type
      values:
        - geth
    - type: num_blocks
      value: 10
    - type: gas_limit
      value: 1000000000
