payloads:
  - name: EC Add Precompile
    id: ecadd
    type: contract
    calls_per_block: 1
    function_signature: ecadd(uint256,bytes)
    gas_per_tx: 10000000

benchmarks:
  - name: EC Add Precompile
    description: EC Add Operation - https://github.com/base/fp-test-cases/blob/main/src/Precompiler.sol
    benchmark:
      - sequencer
    variables:
      - type: payload
        value: ecadd
      - type: node_type
        values:
          - geth
          - reth
      - type: num_blocks
        value: 5
      - type: gas_limit
        value: 1000000000
