payloads:
  - name: ERC 20 Workload
    id: erc20
    type: contract
    calls_per_block: 1
    function_signature: moveErc20(uint256,bytes)
    gas_per_tx: 10000000

benchmarks:
  - name: ERC 20 Workload
    description: https://github.com/base/fp-test-cases/blob/main/src/ERC20Transfer.sol
    benchmark:
      - sequencer
    variables:
      - type: payload
        value: erc20
      - type: node_type
        values:
          - geth
          - reth
      - type: num_blocks
        value: 10
      - type: gas_limit
        value: 1000000000
