- name: Transfer-only execution speed
  description: Tests a block that contains many transactions that repeatedly transfer ETH balance to various addresses.
  variables:
    - type: transaction_workload
      values:
        - transfer-only
    - type: node_type
      values:
        - geth
        - reth
    - type: num_blocks
      value: 10
    - type: gas_limit
      values:
        - 15000000
        - 30000000
        - 60000000
        - 90000000
- name: EC Pairing Precompile
  description: This test creates a block with a single transaction that repeatedly calls EC Pairing precompile.
  benchmark:
    - sequencer
  variables:
    - type: node_type
      values:
        - geth
        - reth
    - type: num_blocks
      value: 5
    - type: gas_limit
      value: 505000000
    - type: transaction_workload
      values:
        - contract:1:ecpairing(uint256,bytes):200000000:0x:./contracts/precompiles.hex
        - contract:1:ecpairing(uint256,bytes):400000000:0x:./contracts/precompiles.hex
- name: EC Mul Precompile
  description: This test creates a block with a single transaction that repeatedly calls EC Mul precompile.
  benchmark:
    - sequencer
  variables:
    - type: transaction_workload
      values:
        - contract:1:ecmul(uint256,bytes):1000000000:0x:
    - type: node_type
      values:
        - geth
        - reth
    - type: num_blocks
      value: 5
    - type: gas_limit
      value: 1005000000
- name: SStore Performance
  description: This test creates a block with a single transaction that repeatedly calls SStore operation.
  benchmark:
    - sequencer
  variables:
    - type: transaction_workload
      values:
        - contract:1:writer(uint256,bytes):1000000000:0x:./contracts/precompiles.hex
    - type: node_type
      values:
        - geth
        - reth
    - type: num_blocks
      value: 5
    - type: gas_limit
      value: 1005000000
