payloads:
  - name: SLoad Performance
    id: sload
    type: contract
    calls_per_block: 1
    function_signature: reader(uint256,bytes)
    gas_per_tx: 10000000
    contract_bytecode: Precompile

benchmarks:
  - name: SLoad Performance
    description: https://github.com/base/fp-test-cases/blob/main/src/Reader.sol
    benchmark:
      - sequencer
    variables:
      - type: payload
        value: sload
      - type: node_type
        values:
          - geth
          - reth
      - type: num_blocks
        value: 5
      - type: gas_limit
        value: 1000000000
