payloads:
  - name: SStore Performance
    id: sstore
    type: contract
    calls_per_block: 1
    function_signature: writer(uint256,bytes)
    gas_per_tx: 10000000

benchmarks:
  - name: SStore Performance
    description: https://github.com/base/fp-test-cases/blob/main/src/Writer.sol
    benchmark:
      - sequencer
    variables:
      - type: payload
        value: sstore
      - type: node_type
        values:
          - geth
          - reth
      - type: num_blocks
        value: 5
      - type: gas_limit
        value: 1000000000
