- name: Test op-node Performance
  description: Reth vs Geth Execution Speed
  benchmark:
    - execution-speed
  variables:
    - type: transaction_workload
      values:
        - tool:tx-fuzz
    - type: node_type
      values:
        - geth