- name: Test op-node Performance
  description: Reth vs Geth Execution Speed
  benchmark:
    - op-program
  variables:
    - type: transaction_workload
    - type: node_type
      values:
        - reth
