- name: Test geth Performance
  description: Geth Execution Speed
  benchmark:
    - sequencer
  variables:
    - type: transaction_workload
      values:
        - tx-fuzz
    - type: node_type
      values:
        - geth
    - type: num_blocks
      value: 20