- name: TX-Fuzz Geth Performance
  description: TX-Fuzz Geth Performance
  variables:
    - type: transaction_workload
      values:
        - tx-fuzz
    - type: node_type
      values:
        - geth
    - type: num_blocks
      value: 20
  