version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - S3_BUCKET=${S3_BUCKET}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CACHE_TTL=5m
      - ENABLE_CACHE=true
      - ALLOWED_ORIGINS=*
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/v1/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
