name: Node.js CI

on:
  push:
    paths:
      - "report/**"
    branches:
      - main
  pull_request:
    paths:
      - "report/**"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./report
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./report/package-lock.json"

      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run check
      - name: Run tests
        run: npm test
